# Generated by Django 4.0.4 on 2022-05-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_tag_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desription',
            new_name='description',
        ),
    ]
