# Generated by Django 4.0.4 on 2022-05-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_image',
            new_name='image',
        ),
    ]
